namespace itembank_index_backend.Models.Definition;

public static class ElasticReservedWord
{
    public static Dictionary<string, string> Mappings = new ()
    {
        { "+", "_PLUS_" },
        { "＋", "_PLUS_" },
        { "-", "_HYPHEN_" },
        { "－", "_HYPHEN_" },
        { "=", "_EQUALS_" },
        { "＝", "_EQUALS_" },
        { "&&", "_LOGICAL_AND_" },
        { "＆＆", "_LOGICAL_AND_" },
        { "||", "_LOGICAL_OR_" },
        { "｜｜", "_LOGICAL_OR_" },
        { ">", "_GREATER_THAN_" },
        { "＞", "_GREATER_THAN_" },
        { "<", "_LESS_THAN_" },
        { "＜", "_LESS_THAN_" },
        { "!", "_EXCLAMATION_" },
        { "！", "_EXCLAMATION_" },
        { "(", "_LEFT_PARENTHESIS_" },
        { "（", "_LEFT_PARENTHESIS_" },
        { ")", "_RIGHT_PARENTHESIS_" },
        { "）", "_RIGHT_PARENTHESIS_" },
        { "{", "_LEFT_BRACE_" },
        { "｛", "_LEFT_BRACE_" },
        { "}", "_RIGHT_BRACE_" },
        { "｝", "_RIGHT_BRACE_" },
        { "[", "_LEFT_BRACKET_" },
        { "［", "_LEFT_BRACKET_" },
        { "]", "_RIGHT_BRACKET_" },
        { "］", "_RIGHT_BRACKET_" },
        { "^", "_CARET_" },
        { "＾", "_CARET_" },
        { "\"", "_QUOTATION_MARK_" },
        { "”", "_QUOTATION_MARK_" },
        { "“", "_QUOTATION_MARK_" },
        { "~", "_TILDE_" },
        { "～", "_TILDE_" },
        { "*", "_ASTERISK_" },
        { "＊", "_ASTERISK_" },
        { "?", "_QUESTION_MARK_" },
        { "？", "_QUESTION_MARK_" },
        { ":", "_COLON_" },
        { "：", "_COLON_" },
        { "\\", "_BACK_SLASH_" },
        { "＼", "_BACK_SLASH_" },
        { "/", "_SLASH_" },
        { "／", "_SLASH_" },
    };

    public static Dictionary<string, string> MappingsReverse = new ()
    {
        { "_PLUS_", "+" },
        { "_HYPHEN_", "-" },
        { "_EQUALS_", "=" },
        { "_LOGICAL_AND_", "&&" },
        { "_LOGICAL_OR_", "||" },
        { "_GREATER_THAN_", ">" },
        { "_LESS_THAN_", "<" },
        { "_EXCLAMATION_", "!" },
        { "_LEFT_PARENTHESIS_", "(" },
        { "_RIGHT_PARENTHESIS_", ")" },
        { "_LEFT_BRACE_", "{" },
        { "_RIGHT_BRACE_", "}" },
        { "_LEFT_BRACKET_", "[" },
        { "_RIGHT_BRACKET_", "]" },
        { "_CARET_", "^" },
        { "_QUOTATION_MARK_", "\"" },
        { "_TILDE_", "~" },
        { "_ASTERISK_", "*" },
        { "_QUESTION_MARK_", "?" },
        { "_COLON_", ":" },
        { "_BACK_SLASH_", "\\" },
        { "_SLASH_", "/" },
    };
}